### ISSUE TITLE
No jar or maven repo

### ISSUE THREAD

**Issue by somghosh** [lawloretienne/QuickReturn#12]
I could not find a jar file for QuickReturn (really great library and with one of the best examples, neatly written). So should I just create a new module in my Android Studio project and copy the contents of /library?

**Comment by clau007** [comment]
Yeah. I suggest you to create a "libraries" folder in your project root and copy the "library" folder in here. You can rename it to "quickreturnlib" or whatever you want.

From android studio open your Gradle Scripts and include into the settings.gradle (Project Settings) file the folder of the new library by adding this row: 

include ':libraries:quickreturnlib'

Then add this dependency to your build.gradle(Module: yourmainprojectname) file:

compile project(':libraries:quickreturn')

Sync your project and start using the library.

**Comment by somghosh** [comment]
Thanks a lot @clau007

**Comment by lawloretienne** [comment]
@somghosh @clau007 Sorry I don't have this up as a maven repo.  I actually have tried to go through the process to turn this into a maven repo but it was really difficult to set up.  If anyone has suggestions or is willing to help me with this, I am all ears.

**Comment by mblcdr** [comment]
@lawloretienne the process of pushing a library to central is indeed a bit complicated. But you can provide an easy to use access for maven and gradle users with JitPack. Take a look here: https://jitpack.io

Also here's the link to how to set it up and update your readme file accordingly for the users:
https://github.com/jitpack/jitpack.io/blob/master/ANDROID.md

**Comment by brianmuse** [comment]
:+1: This would be extremely helpful!

**Comment by jitpack-io** [comment]
@mblcdr Thanks for suggesting! You're absolutely right, it's were easy to publish on JitPack. Only a few tweaks needed and submitted as a PR #20.

Here's how it looks with our forked project: https://jitpack.io/#jitpack-io/QuickReturn/1.0

Will be happy to help deploying @lawloretienne .

**Comment by mblcdr** [comment]
@jitpack-io This library contains xml resources, so I guess it should be deployed as an aar file. Shouldn't the gradle complie setting contain ```@aar``` suffix?

**Comment by jitpack-io** [comment]
@mblcdr If you use it from Gradle it will download the .aar file automatically even if you don't specify `@aar`. Its because Gradle downloads the .pom file and sees that it's an .aar packaging type.

**Comment by nathanjones** [comment]
Thanks @jitpack-io! Packaging up the library like that makes it a heck of a lot easier to use. Would love to see @lawloretienne accept PR #20.

**Comment by lawloretienne** [comment]
I have updated the README with simple setup instructions for Gradle or Maven.
