### ISSUE TITLE
please complateTodo Convert library into an Android archive (.aar)

### ISSUE THREAD

**Issue by saityoukou** [lawloretienne/QuickReturn#13]
nice library
please complateTodo Convert library into an Android archive (.aar)
thank you.

**Comment by lawloretienne** [comment]
@saityoukou I have tried to convert this into an .aar but couldn't figure it out.  Do you know how to do this?

**Comment by rizhilee** [comment]
Perhaps this article will help you, however, is in Chinese.
http://www.trinea.cn/dev-tools/upload-java-jar-or-android-aar-to-maven-center-repository/

**Comment by noman-iqbal** [comment]
This will help you i guess. 
http://stackoverflow.com/questions/24309950/create-aar-file-in-android-studio

**Comment by lawloretienne** [comment]
I have updated the README with simple setup instructions for Gradle or Maven.
