### ISSUE TITLE
InterAPPtiv3 keystore and passwords are in the project in plaintext

### ISSUE THREAD

**Issue by ewhite-dev** [lawloretienne/QuickReturn#16]
Should be included in gitignore instead

**Comment by lawloretienne** [comment]
Thanks for pointing this out.  I have wanted to do this, but am not sure how.  How would I do this?

**Comment by ewhite-dev** [comment]
well, adding to gitignore is a simple command but retroactively removing files from old commits is something I don't know off the top of my head so look at this highly upvoted answer on stackoverflow:

http://stackoverflow.com/a/7532131/727429

**Comment by lawloretienne** [comment]
I was wondering what exactly I would need to add to .gitignore since i have
the password in the build.gradle file.  Would i need to add build.gradle to
.gitignore or do I have to alias the passwords somehow, im just not sure
about how to do that part.

On Wed, Feb 11, 2015 at 11:25 AM, ewhite-dev <notifications@github.com>
wrote:

> well, adding to gitignore is a simple command but retroactively removing
> files from old commits is something I don't know off the top of my head so
> look at this highly upvoted answer on stackoverflow:
>
> http://stackoverflow.com/a/7532131/727429
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lawloretienne/QuickReturn/issues/16#issuecomment-73946436>
> .
>



-- 
-Etienne Lawlor (Software Developer)

**Comment by ewhite-dev** [comment]
After scrubbing the old versions out of the repository, you can commit a version of build.gradle without the `release` part of the script. Locally you can add build.gradle to .gitignore , but I'm not sure what the best best practice is, for instance you may add/change some dependencies and want to commit that build.gradle

It may be possible to have the passwords in a different file that is references by build.gradle, and have that file always ignored. So you can release updates easily but others can't use your keystore and password

**Comment by lawloretienne** [comment]
looks like this explains how to do it

https://www.timroes.de/2013/09/22/handling-signing-configs-with-gradle/

Thanks for pointing this out.  I will get that updated soon.

On Wed, Feb 11, 2015 at 11:45 AM, ewhite-dev <notifications@github.com>
wrote:

> After scrubbing the old versions out of the repository, you can commit a
> version of build.gradle without the release part of the script. Locally
> you can add build.gradle to .gitignore , but I'm not sure what the best
> best practice is, for instance you may add/change some dependencies and
> want to commit that build.gradle
>
> It may be possible to have the passwords in a different file that is
> references by build.gradle, and have that file always ignored. So you can
> release updates easily but others can't use your keystore and password
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lawloretienne/QuickReturn/issues/16#issuecomment-73950390>
> .
>



-- 
-Etienne Lawlor (Software Developer)

**Comment by lawloretienne** [comment]
Thanks @ewhite-dev for bringing this to my attention.

So I followed the steps in this blog post
http://www.thoughtworks.com/insights/blog/signing-open-source-android-apps-without-disclosing-passwords

Then to untrack a file in a git repo (http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore) I just did the following command

git rm --cached <file>
