### ISSUE TITLE
SwipeRefreshLayout support

### ISSUE THREAD

**Issue by fdln** [lawloretienne/QuickReturn#17]
I try using SwipeRefreshLayout as the parent layout
```
<?xml version="1.0" encoding="utf-8"?>

<android.support.v4.widget.SwipeRefreshLayout
    android:id="@+id/the_swiperefreshlayout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/the_recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />

        <TextView
            android:id="@+id/the_textview_for_quickreturn"
            android:layout_width="match_parent"
            android:layout_height="80dp"
            android:layout_alignParentTop="true"
            android:gravity="center"
            android:text="Header"
            android:textColor="@android:color/white"
            android:textSize="22sp"/>
    </RelativeLayout>
</android.support.v4.widget.SwipeRefreshLayout>
```

Its worked for at first load, but then when i scroll down and then scrolled it up again, ProgressBar is showed instead the Header, see image below:

![QuickReturn with SwipeRefreshLayout](https://dl.dropboxusercontent.com/u/6946241/out18.gif)

So how to handle SwipeRefreshLayout with QuickReturn? thanks.

**Comment by oliguo** [comment]
I add this ,it works,
firstly, you should put swipelayout to contain recycleview not root layout,

<RelativeLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
 android:layout_width="match_parent"
        android:layout_height="match_parent">

<android.support.v4.widget.SwipeRefreshLayout
    android:id="@+id/the_swiperefreshlayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/the_recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />

</android.support.v4.widget.SwipeRefreshLayout>

        <TextView
            android:id="@+id/the_textview_for_quickreturn"
            android:layout_width="match_parent"
            android:layout_height="80dp"
            android:layout_alignParentTop="true"
            android:gravity="center"
            android:text="Header"
            android:textColor="@android:color/white"
            android:textSize="22sp"/>
    </RelativeLayout>


and I add code to refresh if first item:

swipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
                    @Override
                    public void onRefresh() {
                        mRecyclerViewTop=mRecyclerView.getChildAt(0).getTop();
                        Log.d("RecycleviewPosition", "init:"+mRecyclerViewTop+";"+ (mRecyclerViewTop-16==0));
                        if ((!isRefresh)&&(mRecyclerViewTop-16==0)) {
                            Log.d("RecycleviewPosition", "get:" + mRecyclerView.getChildAt(0).getTop());
                            isRefresh = true;
                            new Handler().postDelayed(new Runnable() {
                                public void run() {
                                    swipeRefreshLayout.setRefreshing(false);
                                    isRefresh = false;
                                    mRecyclerViewTop=0;
                                }
                            }, 3000);
                        }else{
                            swipeRefreshLayout.setRefreshing(false);
                            isRefresh = false;
                        }
                    }
                });

and the line of code "mRecyclerViewTop-16==0 " the int 16 which get from mRecyclerView.getChildAt(0).getTop()

**Comment by fdln** [comment]
Yes, now it works. Thanks @oliguo
