### ISSUE TITLE
Separate library from examples

### ISSUE THREAD

**Issue by iPaulPro** [lawloretienne/QuickReturn#2]
It's not fun having to search through an entire project just to see how something is fundamentally implemented. This is especially true for ones like this, where the "library" _and_ examples are in the same project. It would be better to create two different projects, library and samples.  Also, a simple example in the README would go a long way.

As it is now, it's completely unclear which dependencies are actually needed, and how to use this as an Android library project.

**Comment by lawloretienne** [comment]
I have updated the README with simple setup instructions for Gradle or Maven.
