### ISSUE TITLE
Support Gradle?

### ISSUE THREAD

**Issue by KingWu** [lawloretienne/QuickReturn#21]
Hi, this is an awesome fork. Can it support gradle?

Thanks

**Comment by lawloretienne** [comment]
I am looking to create a maven artifact so that it will be a one line gradle dependency, but haven't quite figured out how to set that up.  But I definitely have that in mind.

**Comment by jitpack-io** [comment]
@lawloretienne Can help with that:)

**Comment by afollestad** [comment]
You should add it to Bintray, that's what jCenter (the default Android Studio repository) runs on top of.

**Comment by afollestad** [comment]
There's also a convenient Gradle for publishing: https://github.com/novoda/bintray-release

**Comment by lawloretienne** [comment]
I have updated the README with simple setup instructions for Gradle or Maven.
