### ISSUE TITLE
Header above listview at top

### ISSUE THREAD

**Issue by Maxxan** [lawloretienne/QuickReturn#24]
In your examples, the header is above the listview even when the listview is at the top of the list, so the first two items in the list is never visible.

**Comment by lawloretienne** [comment]
Hey Maxxan,
  That was just one of the examples.  Feel free to make a pull request to
add an additional example.

On Tue, May 19, 2015 at 4:03 PM, Maxxan <notifications@github.com> wrote:

> In your examples, the header is above the listview even when the listview
> is at the top of the list, so the first two items in the list is never
> visible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lawloretienne/QuickReturn/issues/24>.
>



-- 
-Etienne Lawlor (Software Developer)

**Comment by Maxxan** [comment]
I would prefer to see a solution to to make it below the header while at
the top, but when the header view is gone, it fills the whole height. I
don't know how to do that..
Den 20 maj 2015 01:08 skrev "Etienne Lawlor" <notifications@github.com>:

> Hey Maxxan,
> That was just one of the examples. Feel free to make a pull request to
> add an additional example.
>

**Comment by lawloretienne** [comment]
I am doing something similar in the Twitter example.  Let me know if you have any questions.  I add a dummy item to the listview the same size as the quick return header.
