### ISSUE TITLE
Cannot hide FooterTextView(Google Plus Implementation)

### ISSUE THREAD

**Issue by rabyunghwa** [lawloretienne/QuickReturn#25]
Hey. In the Google plus' implementation, is there a way to hide the FooterTextView while keeping the FooterImageView? You know, just like in Google plus, when there are no new posts, users can't see the "Touch to see new posts" footer view. I tried to set its visibility to GONE but as soon as I scroll, it appears again, even tho I am sure there are no new posts. It seems to me that the two footer views must appear at the same time when scrolling. Or is there another way to control this behavior? Thanks.

**Comment by lawloretienne** [comment]
So in the xml you would need to set visibility to GONE.  Also in the QuickReturnGooglePlusFragment class, the ScrollListener builder takes a has a method .footerViews() which takes an ArrayList<View> as a param.  If you comment out lines 141 and 142 it wont add the FooterTextView.
