### ISSUE TITLE
Minimum SDK support

### ISSUE THREAD

**Issue by patelakshay13890** [lawloretienne/QuickReturn#26]
What is the Minimum SDK require to run smoothly ??
I required minSDK = 10 or 11, so would it run ??

**Comment by lawloretienne** [comment]
@patelakshay13890 I have updated the README with simple setup instructions for Gradle or Maven.  I am not sure what the minimum SDK is but maybe you could test this and let me know if you are having issues.

**Comment by lawloretienne** [comment]
Closing this for now.  Let me know if you are having issues using the library.
