### ISSUE TITLE
build failed ; Tips :  No such property: GROUP for class

### ISSUE THREAD

**Issue by ikkyu0319** [lawloretienne/QuickReturn#27]
Gradle 'QuickReturn' project refresh failed
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by lawloretienne** [comment]
Sorry about that.  I had gradle.properties in my .gitignore.  Now you can clone and run the project.  Also if you want to include it in your own project look at the README for the Gradle or Maven setup.
