### ISSUE TITLE
Running QuickReturn sample

### ISSUE THREAD

**Issue by dhrumit123** [lawloretienne/QuickReturn#5]
error: No resource identifier found for attribute 'cardCornerRadius' in package 'com.etiennelawlor.quickreturn'

**Comment by feay1234** [comment]
I got the same error when importing the project to eclipse.

**Comment by lawloretienne** [comment]
@feay1234 I have set up my gradle project in Android Studio.  I am not familiar with the exact configuration that is needed to make it run in Eclipse.

**Comment by lawloretienne** [comment]
I have updated the README with simple setup instructions for Gradle or Maven.
