### ISSUE TITLE
Twitter demo pager tab and footer auto disappeared issue

### ISSUE THREAD

**Issue by longkai** [lawloretienne/QuickReturn#6]
In the Twitter demo app, when scroll to the centre page, the tab quick disappear.

also, the bottom got some problems. When you leave the "HOME" page which show the footer, and go to the "Activity" page, the footer disappeared.

Please Fixed, Thanks in advance. I really appreciate what you did.

**Comment by lawloretienne** [comment]
@longkai is this still an issue?

**Comment by longkai** [comment]
It's not. Sorry for the delay, once again.
